{{- include "transcriber.validateSources" . }}
{{- if not .Values.sources.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transcriber.sourcesConfigMapName" . }}
  labels:
    {{- include "transcriber.labels" . | nindent 4 }}
data:
  sources.txt: |-
{{- range .Values.sources.entries }}
    {{ . }}
{{- end }}
{{- end }}