---
name: Publish container image

"on":
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: container-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    uses: docker/github-builder/.github/workflows/build.yml@a492c6d04fd3315f67230809b44d60cc0acd50b3  # v1
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      output: image
      push: true
      platforms: linux/amd64
      cache: true
      cache-scope: transcriber
      meta-images: ghcr.io/michael-c-buckley/transcriber
      meta-tags: |
        type=sha,format=long,prefix=
        type=semver,pattern={{version}}
        type=raw,value=latest,enable={{is_default_branch}}
      set-meta-labels: true
    secrets:
      registry-auths: |-
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
